// eslint-plugin-import
export default {
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/extensions.md
  'import/extensions': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-anonymous-default-export.md
  'import/no-anonymous-default-export': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md
  'import/no-extraneous-dependencies': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-import-module-exports.md
  'import/no-import-module-exports': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md
  'import/no-unresolved': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md
  'import/newline-after-import': 'error',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md
  'import/no-duplicates': 'error',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/prefer-default-export.md
  'import/prefer-default-export': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unassigned-import.md
  'import/no-unassigned-import': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unused-modules.md
  'import/no-unused-modules': 'error',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md
  'import/no-cycle': 'warn',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-named-as-default-member.md
  'import/no-named-as-default-member': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/namespace.md
  'import/namespace': 'off',
  // https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-named-as-default.md
  'import/no-named-as-default': 'off',
};
